export enum foodsParameters {
    title = 'Alimentos',
    buttonNew = 'Nuevo alimento',
    deleteConfirmationMessage = '¿Esta seguro de borrar el alimento?'
}

export enum formParameters {
    creationTitle = 'Crear un nuevo alimento',
    editionTitle = 'Editar alimento',
    nameLabel = 'Nombre del alimento',
    categoriesLabel = 'Categorias',
    referenceMeasurementsTitle = 'Medidas de referencia',
    referenceMassInGramsLabel = 'Gramos',
    referenceVolumeInMililitersLabel = 'Mililitros',
    referenceUnitsLabel = 'Unidades',
    fattyAcidsAndCholesterolTitle = 'Acidos grasos y colesterol',
    saturatedFatLabel = 'Grasa saturada',
    monounsaturatedFatLabel = 'Grasa monosaturada',
    polyunsaturatedFatLabel = 'Grasa poliinsaturada',
    cholesterolLabel = 'Colesterol',
    macronutrientsTitle = 'Macronutrientes ',
    caloriesLabel = 'Calorías',
    proteinLabel = 'Proteína',
    carbohydratesLabel = 'Carbohidratos',
    greaseLabel = 'Grasa',
    fiberLabel = 'Fibra',
    mineralsTitle = 'Minerales',
    calciumLabel = 'Calcio',
    ironLabel = 'Hierro',
    sodiumLabel = 'Sodio',
    phosphorusLabel = 'Fosforo',
    iodoLabel = 'Yodo',
    zincLabel = 'Zinc',
    manganeseLabel = 'Magnesio',
    potassiumLabel = 'Potasio',
    vitaminsTitle = 'Vitaminas',
    thiaminLabel = 'Tiamina',
    riboflavinLabel = 'Riboflavina',
    niacinLabel = 'Niacina',
    folatesLabel = 'Folatos',
    vitaminB12Label = 'Vitamina B12',
    vitaminCLabel = 'Vitamina C',
    vitaminALabel = 'Vitamina A ',
}